<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2017-05-27 10:22:59
 * @@Function:
 */
 ?>
<?php if(!$this->getStatus()) return; ?>
<?php $selector = 'alo-content-'.uniqid(); ?>
<div class= "<?php echo $selector?> magicproduct magiccategory autoplay">
<?php
$tabs = $this->getTabs();
$numTabs = count($tabs);
if($numTabs): ?>
    <div class="magic-category clearfix">
		<div class="block-title-tabs clearfix">
			<h3 class="title title-category"><?php echo __($this->getTitle()); ?></h3>
			<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
			<?php $activated = $this->getTabActivated();
				$limit = $this->getLimit();
				$single = ($numTabs ==1) ? 'single' : '';
				foreach ($tabs as $type => $name):
					$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
					$status .= ($type == $activated) ? " activated $single" : '';
					echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
				endforeach;
			?>
			</ul>
		</div>
	</div>
<?php endif ?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/category', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
	<div class="box-product-content clearfix">
		<div class="box-product">
			<div class="content-products" 
			<?php foreach ($this->getFrontendCfg() as $opt) :?>
				data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
			<?php endforeach;?>
			>
			<?php 
				$timer = $this->getTimer();
				if($timer) echo $this->getContent('category/gridtimer.phtml');	
				else echo $this->getContent('category/grid.phtml');	
			?>
			</div>
		</div>
		<div class="box-product-adv">
			<div class="promotion">
				<img src="<?php echo $this->getMediaUrl() . $this->getImage();?>">
			</div>
	    </div> 
	</div>
</div>
